services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    env_file:
      - .env
    restart: always
    volumes:
      - anythingllm_storage:/app/server/storage
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anythingllm.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.anythingllm.entrypoints=web"
      - "traefik.http.routers.anythingllm.entrypoints=websecure"
      - "traefik.http.routers.anythingllm.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"

  traefik:
    image: traefik:3.0.4
    env_file:
      - .env
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/app-data

networks:
  web:
    driver: bridge